import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, watch, existsSync } from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository.
*/
`;

const prod = process.argv[2] === "production";

const VAULT_PLUGIN_DIR = "vault/.obsidian/plugins/polyphon";

function syncToVault() {
  if (!existsSync(VAULT_PLUGIN_DIR)) return;
  copyFileSync("main.js", `${VAULT_PLUGIN_DIR}/main.js`);
  copyFileSync("styles.css", `${VAULT_PLUGIN_DIR}/styles.css`);
}

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  platform: "node",
  plugins: [
    {
      name: "sync-to-vault",
      setup(build) {
        build.onEnd(() => {
          if (!prod) syncToVault();
        });
      },
    },
  ],
});

if (prod) {
  await context.rebuild();
  copyFileSync("src/styles.css", "styles.css");
  process.exit(0);
} else {
  copyFileSync("src/styles.css", "styles.css");
  watch("src/styles.css", () => {
    copyFileSync("src/styles.css", "styles.css");
    syncToVault();
  });
  await context.watch();
}
